### ISSUE TITLE
posting to server from scaffolding generates response error

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#107]
After creating an app and user scaffolding and running the server by following these steps:

```
tower new demoApp
cd demoApp
npm install .
tower generate scaffold User name: string email: string hasMany:posts
cake db:seed
```

and running the server `node server` I visited the site at localhost.  Everything seemed to be functioning correctly but when I tried submitting a new user, I immediately got an error:

```
127.0.0.1 - - [Thu, 19 Apr 2012 15:27:31 GMT] "GET /users/new HTTP/1.1" 200 - "http://localhost:3000/users" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:11.0) Gecko/20100101 Firefox/11.0"
  Processing by UsersController#create as FORM
  Parameters:
{ user: { name: 'Tamnar', email: 'theLibrarian' },
  action: 'create',
  format: 'form' }

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Responder> has no method 'head'
    at Responder._apiBehavior (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/responder.js:90:19)
    at Responder.toFormat (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/responder.js:65:19)
    at Responder.respond (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/responder.js:41:19)
    at Function.respond (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/responder.js:9:22)
    at UsersController.respondWithStatus (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/resourceful.js:190:41)
    at UsersController.<anonymous> (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/resourceful.js:340:20)
    at /home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/resourceful.js:218:27
    at /home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/model/criteria.js:286:18
    at User.<anonymous> (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/application/shared.js:171:20)
    at User.<anonymous> (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/support/callbacks.js:79:34)
```

Oddly, when I restarted the server, everything seemed to have saved correctly as the new user was there. Repeated attempts produced the same series of events.  As sebastianholtz suggested in Issue#105 ( http://bit.ly/IBaeg3 --now closed)  changing line 90 in response.js from  this.head to this.controller.head caused similar behavior but throws a new error:

```
  127.0.0.1 - - [Thu, 19 Apr 2012 15:39:22 GMT] "GET /users/new HTTP/1.1" 200 - "http://localhost:3000/users" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:11.0) Gecko/20100101 Firefox/11.0"
  Processing by UsersController#create as FORM
  Parameters:
{ user: { name: 'Pizzle', email: 'Puzzle' },
  action: 'create',
  format: 'form' }

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
ReferenceError: formats is not defined
    at UsersController.head (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/server/controller/http.js:20:9)
    at Responder._apiBehavior (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/responder.js:90:30)
    at Responder.toFormat (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/responder.js:65:19)
    at Responder.respond (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/responder.js:41:19)
    at Function.respond (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/responder.js:9:22)
    at UsersController.respondWithStatus (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/resourceful.js:190:41)
    at UsersController.<anonymous> (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/resourceful.js:340:20)
    at /home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/controller/resourceful.js:218:27
    at /home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/model/criteria.js:286:18
    at User.<anonymous> (/home/eric/projects/towerApps/demoApp/node_modules/tower/lib/tower/application/shared.js:171:20)
```

I dont know if the other changes he introduced here: http://bit.ly/IBaXhe would fix my issue or not, as I don't have time now to apply them all.
Thanks.

**Comment by sebastianhoitz** [comment]
Yup, that should fix the issue.

This error was introduced, when node-mime was used to detect which format is requested.

**Comment by lancejpollard** [comment]
@edubkendo Yeah that's an error.

It creates the record because `format[controller.format]` is called after the record is created, but `format[controller.format]` is doing `format["FORM"]` (looking at your error).

That's because this line must not be working:

[/tower/controller/instrumentation.coffee#L65](https://github.com/viatropos/tower/blob/8a47d0caa681c673a9968abbac5ae979d0f952d1/src/tower/controller/instrumentation.coffee#L65)

That code `require('mime').extension(@request.header("content-type"))` needs to be adjusted.  Wanna give it a shot?

**Comment by edubkendo** [comment]
yup, I'll see what I can do

**Comment by edubkendo** [comment]
changing that line to 

``` coffeescript
   require('mime').extension(@controller.request.header("content-type"))
```

causes the format come back as "html" instead of "form" but now it keeps trying to redirect o a page called /custom/1 which then gives the error:

```
No path matches /custom/1
```

Kind of unsure where to look next. If anyone has any hints I'd appreciate them.

**Comment by sebastianhoitz** [comment]
That wrong redirect is listed as an issue here: #104

You could just remove those hardcoded redirects in your local tower installation until we have a fix pushed for that.

**Comment by edubkendo** [comment]
Thanks sebastian. After the change I made to instrumentation.coffee, which I've issued a pull request, and commenting out the custom hardcoded redirects from issue #104 , I am now seeing the expected behavior.  Awesome.

**Comment by edubkendo** [comment]
The recent change back to 

``` coffeescript
    require('mime').extension(@request.header("content-type"))
```

causes the original problem to return, although the error messages no longer show up, it once again tries to post as format:form , and returns an empty page.

**Comment by edubkendo** [comment]
Ok, I have a fix for this in the simple case, which doesn't break any tests:

``` coffeescript
      unless @params.format
        try @params.format = require('mime').extension(@request.header("content-type"))
        if @params.format is "form"
          @params.format = "html"
        @params.format ||= "html"
```

but there are tons of mime types that could possibly come back, and any of those besides "form" will just create the same set of errors all over again, or so it seems to me. 

Something that might also work here, and cover the more general case is something like:

``` coffeescript
unless @params.format is "json"
    @params.format = "html"
```

Since it seems like those are the only two formats tower is actually looking for, but I didn't know how this would effect things like uploading files, etc.  It doesn't seem like tower is actually using the information stored here in @params.format to deal with anything like that, just to decide whether to send back html or json, but I wanted to be sure before I put together a pull request.

**Comment by edubkendo** [comment]
fixed with most recent pull request.
