### ISSUE TITLE
Fix polymorphic associations so they don't incorrectly attempt to find a class with the association's name

### ISSUE THREAD

**Issue by contentfree** [tower-archive/tower#116]
Given:

``` coffeescript
# app/models/comment.coffee
class App.Comment extends Tower.Model
  @belongsTo "commentable", polymorphic: true
```

``` coffeescript
# app/models/post.coffee
class App.Post extends Tower.Model
  @hasMany "comments", as: "commentable"
```

```
# tower console
> comment = new App.Comment()
{ attributes: etc... }
> comment.commentable()
Error: Constant 'App.Commentable' wasn't found
    at Object.constant (/tower/lib/node_modules/tower/lib/tower/application/shared.js:124:15)
    at Object.constant (/tower/lib/node_modules/tower/lib/tower/application/shared.js:122:22)
    at BelongsTo.klass (/tower/lib/node_modules/tower/lib/tower/model/relation.js:113:18)
    at BelongsTo.scoped (/tower/lib/node_modules/tower/lib/tower/model/relation.js:102:19)
    at Comment.relation (/tower/lib/node_modules/tower/lib/tower/model/relations.js:38:95)
    at Comment.commentable (/tower/lib/node_modules/tower/lib/tower/model/relation/belongsTo.js:26:19)
    at repl:1:9
    at REPLServer.eval (repl.js:82:21)
    at Interface.<anonymous> (repl.js:182:12)
    at Interface.emit (events.js:67:17)
```

Is this expected? The test cases in Tower seem to imply that it's working, but there's no just straight up "test a polymorphic relationship" tests

**Comment by contentfree** [comment]
And please don't pay attention to the actual code above. It's a simplified case from my own app where the problem exists.
