### ISSUE TITLE
Running `tower` gives unexpected error/output

### ISSUE THREAD

**Issue by krainboltgreene** [tower-archive/tower#12]
Expected: To see the command help banner/details.

What happened:

```
$ tower
   info  - socket.io started

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot call method 'match' of undefined
    at Object.run (/usr/local/lib/node_modules/tower/lib/tower/command.js:6:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tower/bin/tower:3:33)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by lancejpollard** [comment]
Will update the command line interface today.  See this issue for details:
- https://github.com/viatropos/tower/issues/5

**Comment by lancejpollard** [comment]
Fixed

```
viatropos:lp viatropos$ tower
  Usage: 
    tower [command] [options]

  Commands:
    new <app-name>                    generate a new Tower application in folder "app-name"
    console                           command line prompt to your application
    generate <generator>              generate project files (models, views, controllers, scaffolds, etc.)

  Options:
    -h, --help                        output usage information
    -v, --version                     output version number
```
