### ISSUE TITLE
tower server -e development does not work

### ISSUE THREAD

**Issue by moizr** [tower-archive/tower#120]
Here is the error I see when I try to run the server. If the recommended way to run the application is by calling `node server.js` then I'll just do that but running it using the tower command is more rails like.

```
node.js:201
    throw e; // process.nextTick error, or 'error' event on first tick
          ^
Error: Cannot find module 'mongodb'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Function.lib (/usr/local/lib/node_modules/tower/lib/tower/server/store/mongodb/configuration.js:36:14)
    at Function.initialize (/usr/local/lib/node_modules/tower/lib/tower/server/store/mongodb/database.js:28:22)
    at App.<anonymous> (/usr/local/lib/node_modules/tower/lib/tower/server/store/mongodb.js:46:30)
    at Callback.run (/usr/local/lib/node_modules/tower/lib/tower/support/callbacks.js:207:23)
    at /usr/local/lib/node_modules/tower/lib/tower/support/callbacks.js:117:23
    at /usr/local/lib/node_modules/tower/lib/tower/application/shared.js:164:14
```

**Comment by edubkendo** [comment]
first question, did you do, "npm install . " after creating the new project to install the dependencies in the package.json file?

**Comment by lancejpollard** [comment]
I think this is because when you run `tower server`, it's loading the script from the global installation, which looks like this:

[/bin/tower](https://github.com/viatropos/tower/blob/8da86586adbc3fd4193150945cf40722fe44a3c2/bin/tower)

```
#!/usr/bin/env node

require('../lib/tower').Command.run(process.argv);
```

That then tries to require all of the libraries from your global set of modules.  I haven't quite figured out a good way to do this, because when you do `tower new app` you _want_ it to use the global modules since the path is relative.  But when you do `tower console` and `tower server`, you don't.

It needs to be something like:

```
#!/usr/bin/env node

// process.argv == ['node', 'tower', 'server']
if (process.argv[2] && process.argv[2].match(/new/)
  require('../lib/tower').Command.run(process.argv);
else // will find from local node_modules
  require('tower').Command.run(process.argv);
```

Anyone have a good suggestion?

**Comment by KingScooty** [comment]
I seem to be getting this error when running `node server`. Any ideas?

```
   info  - socket.io started
[Mon, 23 Apr 2012 16:40:33 GMT] INFO Tower development server listening on port 3000

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: failed to connect to [127.0.0.1:27017]
    at [object Object].<anonymous> (/Users/KingScooty/Sites/_dev/app_tower_test/node_modules/mongodb/lib/mongodb/connection/server.js:408:73)
    at [object Object].emit (events.js:88:20)
    at [object Object].<anonymous> (/Users/KingScooty/Sites/_dev/app_tower_test/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:93:15)
    at [object Object].emit (events.js:70:17)
    at Socket.<anonymous> (/Users/KingScooty/Sites/_dev/app_tower_test/node_modules/mongodb/lib/mongodb/connection/connection.js:382:10)
    at Socket.emit (events.js:67:17)
    at Array.0 (net.js:301:14)
    at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by moizr** [comment]
I actually had not run `npm install .` after creating the new project.

I just tried it and now I'm getting errors about a c++ compiler not being available. I just installed Lion so I need to first get the new XCode before I try this.

**Comment by lancejpollard** [comment]
@KingScooty Make sure you have started mongodb.  In a separate terminal window, run:

```
[sudo] mongod
```

If you installed this with homebrew via `brew install mongodb`, they should have given you instructions on how to setup a daemon that automatically starts mongo when your computer restarts.

**Comment by KingScooty** [comment]
A-ha! You know what, that did cross my mind, but i didn't think to actually try it as it wasn't mentioned in the `generate` section of the README. Apologies for the ignorance.

**Comment by lancejpollard** [comment]
No worries, feel free to add it to the README where you think it would fit best.  Cheers.

**Comment by moizr** [comment]
@edubkendo Tried `npm install .` followed by running `tower server -e development` and I'm still not able to start the server

**Comment by edubkendo** [comment]
ah see @viatropos answer, beneath mine.
