### ISSUE TITLE
Issues after scaffolding

### ISSUE THREAD

**Issue by webdesserts** [tower-archive/tower#13]
if I create an app...

```
mcmullins@ubuntu:~/sites$ tower new test
   info  - socket.io started
   create : test/.gitignore
   create : test/.npmignore
   create : test/.slugignore
   create : test/Cakefile
   etc...
```

and run it...

```
mcmullins@ubuntu:~/sites$ cd test
mcmullins@ubuntu:~/sites/test$ node server.js
   info  - socket.io started
[Wed, 29 Feb 2012 00:18:35 GMT] INFO Tower development server listening on port 3000
```

It works fine

But if I scaffold a model...

```
mcmullins@ubuntu:~/sites/test$ tower generate scaffold Post title:string body:text
   info  - socket.io started
   create : app/models/post.coffee
   create : app/views/posts
   create : app/views/posts/_form.coffee
   etc...
```

and then try it again...

```
mcmullins@ubuntu:~/sites/test$ node server.js
   info  - socket.io started

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot read property 'prototype' of undefined
    at /home/mcmullins/sites/test/app/controllers/postsController.coffee:3:199
    at /home/mcmullins/sites/test/app/controllers/postsController.coffee:7:5
    at Object.<anonymous> (/home/mcmullins/sites/test/app/controllers/postsController.coffee:47:4)
    at Object.<anonymous> (/home/mcmullins/sites/test/app/controllers/postsController.coffee:49:4)
    at Module._compile (module.js:441:26)
    at Object..coffee (/home/mcmullins/node_modules/tower/node_modules/coffee-script/lib/coffee-script/coffee-script.js:21:21)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
```

I get this error

**Any thoughts?**

And here is the file it's referencing

``` coffeescript

class Test.PostsController extends Test.ApplicationController
  @param "title"
  @param "body"

  new: ->
    @post = new Test.Post

    @respondWith @post, (format) =>
      format.json => @render json: @post

  create: ->
    @_create (success, failure) =>
      success.json => @render json: @resource
      failure.json => @render status: 404
```

**Comment by lancejpollard** [comment]
Are you running this on ubuntu?  It may be b/c `Test.ApplicationController` isn't loaded, try adding `require './applicationController'` at the top.  This might be b/c paths are loaded in a different order by default on mac vs. linux, so that should be fixed.

**Comment by webdesserts** [comment]
Yes, I'm running on Ubuntu and yep, that fixed it.

I'll use the workaround for now. 

If you have any idea on how to check for launch order I can try to run a test for you.

**Comment by lancejpollard** [comment]
Op, this is why:
- [https://github.com/viatropos/tower/tree/master/src/tower/application/server.coffee#L110](https://github.com/viatropos/tower/blob/79b3cca9f83c5eeba8a5244aee84b09474fbfe36/src/tower/application/server.coffee#L110)

On [line 110](https://github.com/viatropos/tower/blob/79b3cca9f83c5eeba8a5244aee84b09474fbfe36/src/tower/application/server.coffee#L110) I specifically loaded `applicationController` before all the other controllers to prevent this problem.  But on [line  115](https://github.com/viatropos/tower/blob/79b3cca9f83c5eeba8a5244aee84b09474fbfe36/src/tower/application/server.coffee#L115), I only required files matching `/\.(js|coffee/`, which that doesn't :)

``` coffeescript
paths = File.files("#{Tower.root}/app/helpers")
paths = paths.concat File.files("#{Tower.root}/app/models")
paths = paths.concat ["#{Tower.root}/app/controllers/applicationController"]
for path in ["controllers", "mailers", "observers", "presenters", "middleware"]
  paths = paths.concat File.files("#{Tower.root}/app/#{path}")

for path in paths
  require(path) if path.match(/\.(coffee|js)$/)
```

Will fix in next push.
