### ISSUE TITLE
Warning Message from Watchfile due to 'pathfinder' property null

### ISSUE THREAD

**Issue by shibasawa** [tower-archive/tower#134]
I created new basic app using Tower.js generator. All the dependencies are installed, but I got this following warning when I run `node server`

```
/opt/local/lib/node_modules/design.io-stylesheets/lib/design.io-stylesheets.js:12
    pathfinder = project.pathfinder;
                        ^


/opt/local/lib/node_modules/design.io-stylesheets/lib/design.io-stylesheets.js:12
    pathfinder = project.pathfinder;
                        ^

TypeError: Cannot read property 'pathfinder' of null
    at /opt/local/lib/node_modules/design.io-stylesheets/lib/design.io-stylesheets.js:12:25
    at Object.<anonymous> (.:22:32)
    at Module._compile (module.js:441:26)
    at Object.<anonymous> (/opt/local/lib/node_modules/design.io/lib/design.io/project.js:168:22)
    at Object.coffee (/opt/local/lib/node_modules/design.io/node_modules/mint/mint.js:180:18)
    at /opt/local/lib/node_modules/design.io/lib/design.io/project.js:167:21
    at [object Object].<anonymous> (fs.js:123:5)
    at [object Object].emit (events.js:64:17)
    at fs.js:1181:12
    at Object.oncomplete (/opt/local/lib/node_modules/design.io/node_modules/hook.io/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:94:5)
TypeError: Cannot read property 'pathfinder' of null
    at /opt/local/lib/node_modules/design.io-stylesheets/lib/design.io-stylesheets.js:12:25
    at Object.<anonymous> (.:22:32)
    at Module._compile (module.js:441:26)
    at Object.<anonymous> (/opt/local/lib/node_modules/design.io/lib/design.io/project.js:168:22)
    at Object.coffee (/opt/local/lib/node_modules/design.io/node_modules/mint/mint.js:180:18)
    at /opt/local/lib/node_modules/design.io/lib/design.io/project.js:167:21
    at [object Object].<anonymous> (fs.js:123:5)
    at [object Object].emit (events.js:64:17)
    at fs.js:1181:12
    at Object.oncomplete (/opt/local/lib/node_modules/design.io/node_modules/hook.io/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:94:5)

Forever detected script exited with code: 1
Forever restarting script for 1 time
```

**Comment by lancejpollard** [comment]
what was the name of your generated app? this may be because a keyword was used, not quite sure yet.

**Comment by shibasawa** [comment]
my generated app is `my-app`.

I retried it under the name `towerapp` and reinstalled all the dependencies via command :

`sudo npm install underscore underscore.string mongodb redis coffee-resque coffee-script mint tower stylus less uglify-js pathfinder async mocha chai sinon design.io design.io-javascripts design.io-stylesheets knox gzip forever cli-table`

it gave me error messages :

```
> design.io@0.3.1 install /Users/willyjansen/Documents/Private/node-workspace/towerapp/node_modules/design.io
> gem install rb-fsevent rb-inotify --no-ri --no-rdoc

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /opt/local/lib/ruby/gems/1.8 directory.

npm ERR! design.io@0.3.1 install: `gem install rb-fsevent rb-inotify --no-ri --no-rdoc`
npm ERR! `sh "-c" "gem install rb-fsevent rb-inotify --no-ri --no-rdoc"` failed with 1
npm ERR! 
npm ERR! Failed at the design.io@0.3.1 install script.
npm ERR! This is most likely a problem with the design.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gem install rb-fsevent rb-inotify --no-ri --no-rdoc
npm ERR! You can get their info via:
npm ERR!     npm owner ls design.io
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/opt/local/bin/npm" "install" "underscore" "underscore.string" "mongodb" "redis" "coffee-resque" "coffee-script" "mint" "tower" "stylus" "less" "uglify-js" "pathfinder" "async" "mocha" "chai" "sinon" "design.io" "design.io-javascripts" "design.io-stylesheets" "knox" "gzip" "forever" "cli-table"
npm ERR! cwd /Users/willyjansen/Documents/Private/node-workspace/towerapp
npm ERR! node -v v0.6.17
npm ERR! npm -v 1.1.21
npm ERR! code ELIFECYCLE
npm ERR! message design.io@0.3.1 install: `gem install rb-fsevent rb-inotify --no-ri --no-rdoc`
npm ERR! message `sh "-c" "gem install rb-fsevent rb-inotify --no-ri --no-rdoc"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/willyjansen/Documents/Private/node-workspace/towerapp/npm-debug.log
npm not ok
```

but then I retried this command using root privilege and it works!

I applied the same dependencies installation to `my-app` and it also works. Now I don't know what cause the earlier error, perhaps one or two packages were not installed properly yet.

**Comment by cacois** [comment]
For what its worth, I got this error even when using sudo, and solved it by using RVM and switching my default ruby to something other than the OSX system install of 1.8.7.
