### ISSUE TITLE
requires node minimum 0.5.8

### ISSUE THREAD

**Issue by abovethewater** [tower-archive/tower#14]
Just been caught out by this, as I seem to be running an outdated version of node.

installed as per doc 

```
npm install tower -g
```

but trying to generate an app fails due to crypto.randomBytes not appearing in the crypto api until 0.5.8

```
$ tower new app
   info  - socket.io started

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object #<Object> has no method 'randomBytes'
    at AppGenerator.generateRandom (/usr/local/lib/node_modules/tower/lib/tower/generator/resources.js:149:24)
    at AppGenerator.<anonymous> (/usr/local/lib/node_modules/tower/lib/tower/generator/resources.js:140:21)
    at AppGenerator.buildProject (/usr/local/lib/node_modules/tower/lib/tower/generator/generators/tower/app/appGenerator.js:17:51)
    at AppGenerator.Generator (/usr/local/lib/node_modules/tower/lib/tower/generator.js:26:27)
    at new AppGenerator (/usr/local/lib/node_modules/tower/lib/tower/generator/generators/tower/app/appGenerator.js:9:40)
    at Function.run (/usr/local/lib/node_modules/tower/lib/tower/generator.js:11:12)
    at New.run (/usr/local/lib/node_modules/tower/lib/tower/command/new.js:10:28)
    at Object.run (/usr/local/lib/node_modules/tower/lib/tower/command.js:11:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/tower/bin/tower:3:33)
    at Module._compile (module.js:411:26)
```

```
    node -v
    v0.4.12
```

This goes against a comment on another issue that states that it should work for all 0.4.x versions

**Comment by lancejpollard** [comment]
Good find.  `require('crypto').randomBytes(64)` should probably be avoided then, the rest of the app works with at least node 0.4.7 (heroku).  Know of an alternative way to generate random bytes in node 0.4.x?

**Comment by abovethewater** [comment]
If you are simply using it to create a UUID then the following may be useful:

https://github.com/broofa/node-uuid

which in turn references:
https://gist.github.com/982883
https://gist.github.com/1308368

**Comment by lancejpollard** [comment]
Thanks for the fixes, I'm liking that node-uuid library.
