### ISSUE TITLE
Validation fails after specifying message

### ISSUE THREAD

**Issue by marcinrogacki** [tower-archive/tower#146]
I am a beginner of node and tower, so I am not sure if it is a bug. I just followed example from wiki and it does not work.

This works
`@validates 'email', format:  /[a-z0-9_.-]+@[a-z0-9_.-]+\.\w{2,4}/`

But this doesn't:
`@validates 'email', format: { with: /[a-z0-9_.-]+@[a-z0-9_.-]+\.\w{2,4}/, message: 'Invalid email' }`

And an error stack:

``` node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'exec'
    at Format.validate (/home/marcin/Pulpit/newTowerApp/node_modules/tower/lib/tower/model/validator/format.js:23:70)
    at /home/marcin/Pulpit/newTowerApp/node_modules/tower/lib/tower/model/validator.js:112:24
    at /home/marcin/Pulpit/newTowerApp/node_modules/tower/lib/tower/application/shared.js:191:14
    at Array.forEach (native)
    at Object.each (/home/marcin/Pulpit/newTowerApp/node_modules/tower/lib/tower/application/shared.js:144:20)
    at Object.parallel (/home/marcin/Pulpit/newTowerApp/node_modules/tower/lib/tower/application/shared.js:190:18)
    at Format.<anonymous> (/home/marcin/Pulpit/newTowerApp/node_modules/tower/lib/tower/model/validator.js:116:22)
    at Format.check (/home/marcin/Pulpit/newTowerApp/node_modules/tower/lib/tower/model/validator.js:144:23)
    at Format.validateEach (/home/marcin/Pulpit/newTowerApp/node_modules/tower/lib/tower/model/validator.js:107:10)
    at /home/marcin/Pulpit/newTowerApp/node_modules/tower/lib/tower/model/validations.js:36:28
```

**Comment by lancejpollard** [comment]
This is a missing feature right now.  First, you can do `format: {value: /pattern/}`, but not `format: {with: /pattern/}`.  I'm thinking about changing this to match Rails but want to think about it some more first.

Second, the custom `message: 'Invalid email'` key isn't implemented yet.  It's very easy to do, just need to  customize this line here: [/tower/model/validator/format.coffee#L21](https://github.com/viatropos/tower/blob/026416121143dd9a7caf35e9dd1ec5e3ca195dae/src/tower/model/validator/format.coffee#L21).  The other validators need this too, so we just need to refactor.  Will get to this soon unless you would like to submit a pull request.
