### ISSUE TITLE
missing model.errors.uniqueness translation in tower.model.locales

### ISSUE THREAD

**Issue by marcinrogacki** [tower-archive/tower#147]
I tried to use uniqueness validation and got an error.

I noticed that this translation is missing:
https://github.com/viatropos/tower/blob/master/src/tower/model/locale/en.coffee
And I can't change default message in model (my other problem described in issues).

Stack trace:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Translation doesn't exist for 'model.errors.uniqueness'
    at Object.lookup (/home/marcin/Pulpit/testApp/node_modules/tower/lib/tower/support/i18n.js:55:13)
    at Object.<anonymous> (/home/marcin/Pulpit/testApp/node_modules/tower/lib/tower/support/i18n.js:34:34)
    at Object.t (/home/marcin/Pulpit/testApp/node_modules/tower/lib/tower/application/shared.js:74:50)
    at MongoDB.<anonymous> (/home/marcin/Pulpit/testApp/node_modules/tower/lib/tower/model/validator/uniqueness.js:25:63)
    at /home/marcin/Pulpit/testApp/node_modules/tower/lib/tower/server/store/mongodb/finders.js:63:25
    at [object Object].<anonymous> (/home/marcin/Pulpit/testApp/node_modules/mongodb/lib/mongodb/collection.js:517:7)
    at [object Object].g (events.js:156:14)
    at [object Object].emit (events.js:88:20)
    at Db._callHandler (/home/marcin/Pulpit/testApp/node_modules/mongodb/lib/mongodb/db.js:1290:25)
    at /home/marcin/Pulpit/testApp/node_modules/mongodb/lib/mongodb/connection/server.js:329:30
```

**Comment by lancejpollard** [comment]
Fixed in master.
