### ISSUE TITLE
length validations

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#157]
The other validations I've tried seem to work fine, but the length validations appear to be broken.  I've tried setting both maximums and minimums, using first the examples from the wiki, then looking into the length validations methods itself and trying out the different methods there.  In all these cases, the validation simply prevents ANY posts from being created.  I put a console.log in the controller to see what was going on and got recorded these errors, which I'm putting here along with the different variations on the length validation that I tried.

First, following the example from the wiki:

```
@validates "body", length: { maximum: 140, tooLong: "%{count} characters is the maximum allowed" }
```

causes @post.errors:

```
 body: [ 'body must be equal to [object Object]' ] 
```

Similarly:

```
@validates 'body', length: { min: 10 }
```

produces:

```
 body: [ 'body must be equal to [object Object]'
```

So, trying 

```
@validates 'body', min: 10
```

creates:

```
body: [ 'body must be a minimum of 10' ]
```

This error is the same whether the post exactly 10 characters, less than 10 characters or more than 10 characters long.  Trying out max, lte, gte, and etc all produced the same sort of result.

**Comment by edubkendo** [comment]
So looking at tower's code here, it appears that the length validation and related methods all actually work on numbers, not strings (which is what is implied by both the name "length" and the examples in the wiki). I verified this by making a few examples and trying them out and it is definitely the case. For instance:

```
@validates 'lols', length: 10
```

works when 'lols' is a field which takes an integer, and you give it the number 10. 

```
@validates 'lols', max: 10
```

Works similarly, except allows 10 and less to pass, while failing 11 and up.  I don't think, at least on length itself, that this is what was intended, though we definitely NEED validations for testing numbers, we also need validations to test the length of strings. But, not 100% sure what the intent was here...

**Comment by edubkendo** [comment]
Looks like the uniqueness validation also has errors.  Setting a uniqueness vld on my post model:

```
  @validates 'title', uniqueness: true
```

 and trying to create an identical post, triggers this error:

``` node
Error: Translation doesn't exist for 'model.errors.uniqueness'
    at Object.lookup (/home/eric/git/community/tower/lib/tower/support/i18n.js:55:13)
    at Object.<anonymous> (/home/eric/git/community/tower/lib/tower/support/i18n.js:34:34)
    at Object.t (/home/eric/git/community/tower/lib/tower/application/shared.js:74:50)
    at MongoDB.<anonymous> (/home/eric/git/community/tower/lib/tower/model/validator/uniqueness.js:25:63)
    at /home/eric/git/community/tower/lib/tower/server/store/mongodb/finders.js:63:25
    at [object Object].<anonymous> (/home/eric/git/community/tower/node_modules/mongodb/lib/mongodb/collection.js:521:7)
    at [object Object].g (events.js:156:14)
    at [object Object].emit (events.js:88:20)
    at Db._callHandler (/home/eric/git/community/tower/node_modules/mongodb/lib/mongodb/db.js:1296:25)
    at /home/eric/git/community/tower/node_modules/mongodb/lib/mongodb/connection/server.js:386:30
```

**Comment by edubkendo** [comment]
Once pull request #159 and #160 are accepted, this issue will be resolved, so I'm going to go ahead and close it.
