### ISSUE TITLE
npm install for a new app fails on MacOS 10.8

### ISSUE THREAD

**Issue by avaranovich** [tower-archive/tower#170]
Hi there,

When I try this:

tower new app
cd app
npm install

I am getting 
npm http 304 https://registry.npmjs.org/options

> ws@0.4.21 install /Users/avaranovich/projects/source/app/node_modules/design.io/node_modules/hook.io/node_modules/socket.io-client/node_modules/ws
> node install.js

[ws v0.4.21] Attempting to compile blazing fast native extensions.
[ws v0.4.21] Native code compile failed (but the module will still work):
[ws v0.4.21] The native extensions are faster, but not required.
[ws v0.4.21] On Windows, native extensions require Visual Studio and Python.
[ws v0.4.21] On Unix, native extensions require Python, make and a C++ compiler.
[ws v0.4.21] Start npm with --ws:verbose to show compilation output (if any).

I guess that's because the native modules cannot be compiled with LLVM-based GCC ships with MacOS
Once I try to compile with the native GCC (by puting its PATH before the Apple GCC PATH), I get this
...
npm http GET https://registry.npmjs.org/xmlhttprequest/1.2.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
  CXX(target) Release/obj.target/weakref/src/weakref.o
npm c++: error: unrecognized command line option ‘-Wnewline-eof’
http 304 https://registry.npmjs.org/request
make: **\* [Release/obj.target/weakref/src/weakref.o] Error 1
gyp ERR! rebuild error Error: `make` failed with exit code: 2
gyp npm http 304 https://registry.npmjs.org/timespan
ERR! rebuild error     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:215:23)
gyp ERR! rebuild error     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok 
...

node --version
v0.8.2

npm --version
1.1.39

Anyone experiencing the same issue? Any hints/ideas how to address it?

Thanks,
Andrei

**Comment by avaranovich** [comment]
Closing the issue since it was a module-related.
