### ISSUE TITLE
Tower production server fails to start

### ISSUE THREAD

**Issue by avaranovich** [tower-archive/tower#172]
tower s -e production
path.existsSync is now called `fs.existsSync`.
   info  - socket.io started
[Thu, 19 Jul 2012 11:15:31 GMT] INFO Tower production server listening on port 3000

module.js:340
    throw err;
    ^
Error: Cannot find module './daemon.v0.8.2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/forever/node_modules/daemon/lib/daemon.js:12:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

node --version
v0.8.2

node_modules/daemon/lib
has 2 files: daemon.js and daemon.v0.8.2.node

Any ideas?

**Comment by lancejpollard** [comment]
Try clearing your global npm cache and reinstalling some of the modules:

```
npm cache clean -g
npm uninstall forever tower -g
npm install forever tower -g
```

**Comment by avaranovich** [comment]
It solved the issue indeed. Thanks!
