### ISSUE TITLE
TypeError: Cannot call method 'all' of undefined

### ISSUE THREAD

**Issue by jiahut** [tower-archive/tower#174]
I had installed  tower  successful and begin a demo with monogdb like this 

> tower new demo
> cd demo
> tower generate scaffold Post title:string body:text belongsTo:user
> tower generate scaffold User email:string firstName:string lastName:string hasMany:posts
> node server
> [Wed, 25 Jul 2012 16:58:49 GMT] INFO Tower development server listening on port 3000 ]

but ,when I access  "http://localhost:3000/posts" , it respones 

TypeError: Cannot call method 'all' of undefined
    at App.ApplicationController.ApplicationController.bootstrap._.series.App.Post.all.data.posts (E:\node\projects\demo\app\controllers\applicationController.coffee:31:27)
    at async.series.results (D:\dev\nodejs\nodejs_v.0.8.3\deps\node_modules\tower\node_modules\async\lib\async.js:486:21)
    at _asyncMap (D:\dev\nodejs\nodejs_v.0.8.3\deps\node_modules\tower\node_modules\async\lib\async.js:185:13)
    at async.forEachSeries.iterate (D:\dev\nodejs\nodejs_v.0.8.3\deps\node_modules\tower\node_modules\async\lib\async.js:108:13)
    at async.forEachSeries (D:\dev\nodejs\nodejs_v.0.8.3\deps\node_modules\tower\node_modules\async\lib\async.js:124:9)
    at _asyncMap (D:\dev\nodejs\nodejs_v.0.8.3\deps\node_modules\tower\node_modules\async\lib\async.js:184:9)
    at Object.doSeries [as mapSeries](D:devnodejsnodejs_v.0.8.3depsnode_modulestowernode_modulesasynclibasync.js:174:23)
    at Object.async.series (D:\dev\nodejs\nodejs_v.0.8.3\deps\node_modules\tower\node_modules\async\lib\async.js:484:19)
    at Function.asyncing.series (D:\dev\nodejs\nodejs_v.0.8.3\deps\node_modules\tower\lib\tower\support\format.js:252:51)
    at ApplicationController.App.ApplicationController.ApplicationController.bootstrap (E:\node\projects\demo\app\controllers\applicationController.coffee:29:16)

what's worng?
 thinks.

**Comment by lancejpollard** [comment]
Something isn't right with `App.ApplicationController.ApplicationController`.

**Comment by jiahut** [comment]
do not support nodejs_v.0.8.3 ? I didn't write any code until encounter problem.

**Comment by krainboltgreene** [comment]
I don't know Tower.js enough yet, but I have screwed up a lot in Rails. This makes me think there's an auto-loading problem, in that the model hasn't been instantiated yet (aka before the `Model.all` call).

**Comment by lancejpollard** [comment]
Closing this issue unless there are still issues with it.
