### ISSUE TITLE
Error on $ tower (DEVELOPMENT)

### ISSUE THREAD

**Issue by krainboltgreene** [tower-archive/tower#183]
From the development branch:

``` javascript
tower -v

module.js:340
    throw err;
          ^
Error: Cannot find module '../lib/tower'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tower/bin/tower:3:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
```

Freshly installed from folder.

**Comment by krainboltgreene** [comment]
Looks like you know about this from Issue #120, so I'll just try to fix it.

**Comment by lancejpollard** [comment]
fixed now.
