### ISSUE TITLE
Two errors when running design.io or node server.js after updating to most recent commits on the development branch

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#211]
Master was having some other issues for me, so I've been temporarily using the most recent development commit, since it's functional. I imagine these errors will also be present in master, since development is mostly replacing it.

Get these two errors a bunch of times when running "design.io" or "node server.js" in a newly generated app with the most recent pushes to Tower's development branch.

TypeError: Cannot read property 'session' of undefined
    at csrfMetaTag (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at csrfMetaTag (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at eval (eval at <anonymous> (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10)))
    at partial (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at partial (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at body.role (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at Object.__cc.render_contents (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at Object.__cc.render_tag (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at tag (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at Object.__cc.tag (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))

TypeError: Cannot call method 'toLabel' of undefined
    at eval (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at eval (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at Object.coffeecup.render (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:450:10)
    at Tower.ViewRendering._renderCoffeecupString (/home/eric/git/clones/tower/packages/tower-view/shared/rendering.coffee:147:28)
    at Tower.ViewRendering._renderString (/home/eric/git/clones/tower/packages/tower-view/shared/rendering.coffee:112:21)
    at Tower.ViewRendering._renderBody (/home/eric/git/clones/tower/packages/tower-view/shared/rendering.coffee:93:21)
    at Tower.ViewRendering.render (/home/eric/git/clones/tower/packages/tower-view/shared/rendering.coffee:35:19)
    at watch.update.iterator (.:108:18)
    at async.forEachSeries.iterate (/home/eric/projects/projects/towerApps/funApp/node_modules/async/lib/async.js:108:13)
    at async.forEachSeries.iterate (/home/eric/projects/projects/towerApps/funApp/node_modules/async/lib/async.js:119:25)

TypeError: Cannot call method 'toLabel' of undefined
    at eval (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at eval (eval at <anonymous> (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:419:10))
    at Object.coffeecup.render (/home/eric/git/clones/tower/node_modules/coffeecup/lib/coffeecup.js:450:10)
    at Tower.ViewRendering._renderCoffeecupString (/home/eric/git/clones/tower/packages/tower-view/shared/rendering.coffee:147:28)
    at Tower.ViewRendering._renderString (/home/eric/git/clones/tower/packages/tower-view/shared/rendering.coffee:112:21)
    at Tower.ViewRendering._renderBody (/home/eric/git/clones/tower/packages/tower-view/shared/rendering.coffee:93:21)
    at Tower.ViewRendering.render (/home/eric/git/clones/tower/packages/tower-view/shared/rendering.coffee:35:19)
    at watch.update.iterator (.:108:18)
    at async.forEachSeries.iterate (/home/eric/projects/projects/towerApps/funApp/node_modules/async/lib/async.js:108:13)
    at async.forEachSeries.iterate (/home/eric/projects/projects/towerApps/funApp/node_modules/async/lib/async.js:119:25)

**Comment by lancejpollard** [comment]
https://gist.github.com/3422483#comments

**Comment by edubkendo** [comment]
The "toLabel()" error actually gets fixed by my pull request, so that just leaves the other one.

**Comment by lancejpollard** [comment]
nice, will take a look.

**Comment by edubkendo** [comment]
These are cleaned up now.
