### ISSUE TITLE
tower 0.4.2-pre

### ISSUE THREAD

**Issue by j-mcnally** [tower-archive/tower#271]
When i run whats in the repo i get

```
Error: Cannot find module '../lib/tower'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/justin/npm/tower/bin/tower:2:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
```

**Comment by lancejpollard** [comment]
This is from cloning the repo right? If so, you must compile it. In the tower repo directory, run this:

```
make watch
```

Does that fix it? Maybe later we'll keep a .zip of the compiled js in `lib` hosted on GitHub Downloads or something, so if `make watch` isn't run it will still work.

**Comment by lancejpollard** [comment]
This is fixed now, you can also install it from npm.

**Comment by j-mcnally** [comment]
The `make watch` fixed it for me, however i still needed to run `make watc`h when install via `npm install tower -g`
