### ISSUE TITLE
mongodb and forever are missing on new generated app

### ISSUE THREAD

**Issue by lancejpollard** [tower-archive/tower#31]
After you generate a new app, you have to run:

```
npm install forever mongodb
```

This should be done automatically.

**Comment by ghost** [comment]
npm version is 1.1.2 and node is v0.6.12-pre

installation was fine and I created a new tower app via 
    tower new towertestapp

when i tried to start it via node server.js it told me mongodb was missing, I installed it and then it told me forever was missing, installed that too.
then node server.js is working and I can acces the welcome page
system is ubuntu 11.10 by the way

**Comment by lancejpollard** [comment]
Did you run `npm install` in your project directory after you generated the app?  If not, it might be loading the global tower installation, which doesn't include mongodb and forever because it's (I think) installing only `dependencies`, not `devDependencies` which is desired (e.g. you don't need `forever` in production, and you might want to switch out `postgres` for `mongodb`, etc.).

**Comment by ghost** [comment]
didnt know that. will try that out! thanks

**Comment by ghost** [comment]
alright did the tower new towertestapp and ran npm install and i get the following

```

> microtime@0.2.0 install /home/david/development/towertestapp/node_modules/forever/node_modules/microtime
> node-waf configure build

Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 14, in <module>
    import Scripting
ImportError: No module named Scripting
npm ERR! error installing microtime@0.2.0
npm ERR! error installing forever@0.8.5
npm http GET https://registry.npmjs.org/mkdirp
npm ERR! error rolling back forever@0.8.5 Error: UNKNOWN, unknown error '/home/david/development/towertestapp/node_modules/forever/node_modules/___flatiron.npm/package/examples'

npm ERR! microtime@0.2.0 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the microtime@0.2.0 install script.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.0.0-16-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/david/development/towertestapp
npm ERR! node -v v0.6.12-pre
npm ERR! npm -v 1.1.2
npm ERR! code ELIFECYCLE
npm ERR! message microtime@0.2.0 install: `node-waf configure build`
npm ERR! message `sh "-c" "node-waf configure build"` failed with 1
npm ERR! errno {}
npm http GET https://registry.npmjs.org/lru-cache

npm ERR! Error: ENOENT, no such file or directory '/home/david/development/towertestapp/node_modules/forever/node_modules/___utile.npm/package/lib/file.js'
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 3.0.0-16-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/david/development/towertestapp
npm ERR! node -v v0.6.12-pre
npm ERR! npm -v 1.1.2
npm ERR! path /home/david/development/towertestapp/node_modules/forever/node_modules/___utile.npm/package/lib/file.js
npm ERR! fstream_path /home/david/development/towertestapp/node_modules/forever/node_modules/___utile.npm/package/lib/file.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! message ENOENT, no such file or directory '/home/david/development/towertestapp/node_modules/forever/node_modules/___utile.npm/package/lib/file.js'
npm ERR! errno {}
npm ERR! fstream_stack Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:204:26)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/david/development/towertestapp/npm-debug.log
npm not ok
```

**Comment by chrixian** [comment]
These last few errors you posted aren't a tower.js issue, they have to do with node-waf not being properly symlinked if memory serves.  There is a good chance it will fix it self if you upgrade to node v0.6.12 release from the 12-pre and NPM to 1.1.4 and once those are installed do a `npm cache clean` and it should work.

**Comment by ghost** [comment]
good stuff will do. thanks for your help

**Comment by ghost** [comment]
upgrade node to v0.6.12 and update npm
did npm cache clean and ran npm install within the project folder again and getting

```

npm http GET https://registry.npmjs.org/loggly
npm http GET https://registry.npmjs.org/stack-trace
not found 
/home/david/development/towertestapp/node_modules/design.io/node_modules/hook.io/node_modules/mdns/wscript:28: error: the configuration failed (see '/home/david/development/towertestapp/node_modules/design.io/node_modules/hook.io/node_modules/mdns/out/config.log')
npm ERR! error installing mdns@0.0.5
npm ERR! error installing hook.io@0.8.7-1
npm http 304 https://registry.npmjs.org/ini
npm ERR! error rolling back hook.io@0.8.7-1 Error: UNKNOWN, unknown error '/home/david/development/towertestapp/node_modules/design.io/node_modules/hook.io/node_modules/___npm.npm/package/lib/utils/npm-registry-client'
npm ERR! error installing design.io@0.3.0-6
npm http 304 https://registry.npmjs.org/stack-trace

npm ERR! Error: ENOENT, no such file or directory '/home/david/development/towertestapp/node_modules/design.io/node_modules/hook.io/node_modules/___socket.io-client.npm/package/lib/vendor/web-socket-js/flash-src/com/hurlant/crypto/symmetric/NullPad.as'
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 3.0.0-16-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/david/development/towertestapp
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! path /home/david/development/towertestapp/node_modules/design.io/node_modules/hook.io/node_modules/___socket.io-client.npm/package/lib/vendor/web-socket-js/flash-src/com/hurlant/crypto/symmetric/NullPad.as
npm ERR! fstream_path /home/david/development/towertestapp/node_modules/design.io/node_modules/hook.io/node_modules/___socket.io-client.npm/package/lib/vendor/web-socket-js/flash-src/com/hurlant/crypto/symmetric/NullPad.as
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! message ENOENT, no such file or directory '/home/david/development/towertestapp/node_modules/design.io/node_modules/hook.io/node_modules/___socket.io-client.npm/package/lib/vendor/web-socket-js/flash-src/com/hurlant/crypto/symmetric/NullPad.as'
npm ERR! errno {}
npm ERR! fstream_stack Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/fstream/lib/writer.js:285:17)
npm http 304 https://registry.npmjs.org/redis/0.6.7
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm ERR! error rolling back design.io@0.3.0-6 Error: UNKNOWN, unknown error '/home/david/development/towertestapp/node_modules/design.io/node_modules/hook.io/node_modules/nconf/node_modules/___ini.npm/package/test'

npm ERR! mdns@0.0.5 preinstall: `node-waf clean || (exit 0); node-waf configure build`
npm ERR! `sh "-c" "node-waf clean || (exit 0); node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the mdns@0.0.5 preinstall script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || (exit 0); node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.0.0-16-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/david/development/towertestapp
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message mdns@0.0.5 preinstall: `node-waf clean || (exit 0); node-waf configure build`
npm ERR! message `sh "-c" "node-waf clean || (exit 0); node-waf configure build"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/david/development/towertestapp/npm-debug.log
npm not ok
```

**Comment by chrixian** [comment]
Are you running ArchLinux by any chance?

**Comment by chrixian** [comment]
Rather than wait for you to say yes or no I'll just throw a few more suggestions out there... 

1) Are you building from source by checking node out from github or are you installing via a package manage of some kind? If you are using a package manager you need to check if there is an additional dev tools package, somethin like 'node-dev' or 'nodejs-dev', etc. etc. If you're building from github then you have the dev tools.

2) Check what version of python your system runs by default when you enter `python` at the prompt... node-waf needs Python 2.6 so make sure the `python` command doesn't point to Python 2.4 or 3.0 etc.

**Comment by ghost** [comment]
my first comment on top included that its ubuntu. the live systems are freebsd.
node is build from github source and python version is 2.7.2+
had to get some sleep because it was 3 am in the morning at my last post :)

**Comment by ghost** [comment]
alright i did the "tower new towerapp" again just to make sure everything is clean.
I did "sudo npm update -g" just to make sure everything is up-to-date
npm is version 1.1.4 and node is version v0.6.12
then I did npm install within the project folder. so far so good write?!

```

> microtime@0.2.0 install /home/david/development/towerapp/node_modules/forever/node_modules/microtime
> node-waf configure build

Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 14, in <module>
    import Scripting
ImportError: No module named Scripting
npm ERR! error installing microtime@0.2.0
npm ERR! error installing forever@0.8.5
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/lru-cache
npm ERR! error installing timespan@2.0.1
npm ERR! error rolling back forever@0.8.5 Error: UNKNOWN, unknown error '/home/david/development/towerapp/node_modules/forever/node_modules/___utile.npm/package/lib'

npm ERR! microtime@0.2.0 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the microtime@0.2.0 install script.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.0.0-16-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/david/development/towerapp
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message microtime@0.2.0 install: `node-waf configure build`
npm ERR! message `sh "-c" "node-waf configure build"` failed with 1
npm ERR! errno {}
npm http 304 https://registry.npmjs.org/hashish
npm http 304 https://registry.npmjs.org/chainsaw

npm ERR! Error: ENOENT, no such file or directory '/home/david/development/towerapp/node_modules/forever/node_modules/___optimist.npm/package/examples/line_count.js'
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 3.0.0-16-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/david/development/towerapp
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! path /home/david/development/towerapp/node_modules/forever/node_modules/___optimist.npm/package/examples/line_count.js
npm ERR! code ENOENT
npm ERR! message ENOENT, no such file or directory '/home/david/development/towerapp/node_modules/forever/node_modules/___optimist.npm/package/examples/line_count.js'
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/david/development/towerapp/npm-debug.log
npm not ok
```

**Comment by ghost** [comment]
issue seems with node-waf that it cant import Scripting if i run it as user.
can you close the issue cause it has nothing to do directly with tower. if I got any new or other issues related to tower i will open a new issue.
I have a blank arch machine here and will do a clean node and npm install and then test tower again.

thanks guys

**Comment by ghost** [comment]
after i did the above steps and did "sudo npm install" within the project it works ^^
