### ISSUE TITLE
Tower::Fields::Serializable doesn't exist.

### ISSUE THREAD

**Issue by raisch** [tower-archive/tower#336]
Following the Model docs, I attempted to use the field serialization/deserialization example which crashed my server with:

```
/opt/projects/CMS/cmsapp/app/models/shared/point.coffee:12
     include(Tower.prototype.Field.prototype.Serializable);
                       ^
TypeError: Cannot read property 'Field' of undefined
    at /opt/projects/CMS/cmsapp/app/models/shared/point.coffee:12:28
    at Object.<anonymous> (/opt/projects/CMS/cmsapp/app/models/shared/point.coffee:27:5)
    at Object.<anonymous> (/opt/projects/CMS/cmsapp/app/models/shared/point.coffee:29:4)
    at Module._compile (module.js:449:26)
    at Object.require.extensions..coffee (/opt/projects/CMS/cmsapp/node_modules/coffee-script/lib/coffee-script/coffee-script.js:22:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Tower.Application.Application.reopen._requirePaths (/opt/projects/CMS/cmsapp/node_modules/tower/lib/tower-application/server/application.js:334:23)
```

Tower 0.4.2-20
Node  v0.8.6

**Comment by lancejpollard** [comment]
That example (and the docs on the site) are out of date (will be updated soon). That functionality is already included in the model so you don't need to include it directly.

Does that solve your issue? If not, paste your model code, that will help. Thanks!
