### ISSUE TITLE
cake watch issue on Mac OSX Mountain lion "+cmd"?

### ISSUE THREAD

**Issue by TimothyMischief** [tower-archive/tower#364]
New to tower today. After install running "cake watch" from terminal gives:

```
/Users/tim/development/gamehotspot/node_modules/which/which.js:83
  throw new Error("not found: "+cmd)
        ^
Error: not found: grunt
    at whichSync (/Users/tim/development/gamehotspot/node_modules/which/which.js:83:9)
    at spawnGrunt (/Users/tim/development/gamehotspot/Cakefile:20:13)
    at Object.Tower.ApplicationAssets.bundle.minify [as action] (/Users/tim/development/gamehotspot/Cakefile:33:12)
    at helpers.extend.invoke (/usr/lib/node_modules/coffee-script/lib/coffee-script/cake.js:44:26)
    at Object.exports.run (/usr/lib/node_modules/coffee-script/lib/coffee-script/cake.js:69:21)
    at Object.<anonymous> (/usr/lib/node_modules/coffee-script/bin/cake:7:38)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Still relatively new to Node in general also, but from the outside without trawling through source it looks like something to do with a Windows fix? I would assume with "+cmd" in there. That's really just wild speculation though.

**Comment by edubkendo** [comment]
do you happen to have grunt installed globally? Try `npm install -g grunt` and then see if cake watch works.

**Comment by TimothyMischief** [comment]
That's fixed it! Thanks.

**Comment by edubkendo** [comment]
Good deal!

**Comment by ghost** [comment]
still doesn't work after running npm install -g grunt

**Comment by lancejpollard** [comment]
see #388

**Comment by pocesar** [comment]
for the current version of tower, npm should be `npm install grunt@~0.3.0 -g`
