### ISSUE TITLE
Object [operating system] has no method 'match'

### ISSUE THREAD

**Issue by robblovell** [tower-archive/tower#375]
I am just starting with a fresh copy of tower and trying to make the basic application of posts to try and figure out how this thing works.  I do the commands to install, and create an application with the scaffolding, then I start the server.    I have tired it on osx and in windows 7.  Browsing to localhost:3000 (in firefox or chrome) I get the same error: TypeError: "Object [insert some o/s here] has no method 'match'".

Commands to recreate the error:

<pre>
npm install tower -g
tower new towertest
cd towertest
npm install
tower generate scaffold Post title:string body:text
node server
</pre>

browsing to the localhost:3000 url I get:

<pre>
TypeError: Object Windows 7 has no method 'match'
    at Object.Tower.MiddlewareAgent [as handle] (C:\Code\js\towertest\node_modules\tower\lib\tower-middleware\server\agent.js:13:21)
    at next (C:\Code\js\towertest\node_modules\tower\node_modules\connect\lib\proto.js:199:15)
    at Object.handle (C:\Code\js\towertest\app\config\server\bootstrap.coffee:23:14)
    at next (C:\Code\js\towertest\node_modules\tower\node_modules\connect\lib\proto.js:199:15)
    at Object.methodOverride [as handle] (C:\Code\js\towertest\node_modules\tower\node_modules\connect\lib\middleware\methodOverride.js:37:5)
    at next (C:\Code\js\towertest\node_modules\tower\node_modules\connect\lib\proto.js:199:15)
    at multipart (C:\Code\js\towertest\node_modules\tower\node_modules\connect\lib\middleware\multipart.js:64:37)
    at module.exports (C:\Code\js\towertest\node_modules\tower\node_modules\connect\lib\middleware\bodyParser.js:57:9)
    at urlencoded (C:\Code\js\towertest\node_modules\tower\node_modules\connect\lib\middleware\urlencoded.js:51:37)
    at module.exports (C:\Code\js\towertest\node_modules\tower\node_modules\connect\lib\middleware\bodyParser.js:55:7)
</pre>

What am I missing? Shouldn't this just work?

**Comment by DiegoSalazar** [comment]
I get the same thing. I also tried running 

``` javascript
 ➔ cake watch
Default database not set, using Memory store
Running "copy:stylesheets" (copy) task
Copied 2 files.

Running "copy:javascripts" (copy) task
Copied 35 files.

Running "copy:images" (copy) task
Copied 0 files.

Running "coffee:compile" (coffee) task

Running "less:bootstrap" (less) task
File public/stylesheets/vendor/stylesheets/bootstrap/bootstrap.css created.

Running "stylus:compile" (stylus) task
File public/stylesheets/app/stylesheets/client/application.css created.

Running "templates:compile" (templates) task

Running "watch" task
Waiting...
```

but the same error comes up even after a server restart. Not sure where to go from here

**Comment by stevenrace** [comment]
Just chiming in to point out I have this problem as well.

Fresh clone,  archlinux, etc...

**Comment by thehydroimpulse** [comment]
This has been fixed in a pull request: https://github.com/viatropos/tower/pull/376 though it hasn't been merged yet.

**Comment by stevenrace** [comment]
Awesome, but the issue #376 link is '500'ing at the moment.  :/

Can you post of the change in a gist or something in the meantime?

**Comment by gawnecoding** [comment]
As a quick workaround I set the flags on lines 13-15 of C:\Code\js\towertest\node_modules\tower\lib\tower-middleware\server\agent.js manually:

...
mac: false,
windows: true,
linux: false
...

**Comment by SebastianThiebaud** [comment]
Thank you so much @gawnecoding. Works perfectly with your update.

**Comment by o-nix** [comment]
Found this bug today on my Windows 7. Thanks @gawnecoding.

**Comment by cramhead** [comment]
Works for me. Thanks

**Comment by curioushuman** [comment]
Diamond @gawnecoding - great temp fix.

**Comment by Tolmark12** [comment]
Worked for me, thanks, will this be addressed in a more permanent way?

**Comment by thehydroimpulse** [comment]
Not sure if the pull request didn't go through or if the npm version isn't
up to date with the repo.

Either way, were working hard on 0.5.0 which will dramatically change
things up. Thats why these issues might not be the first priority.

**Comment by lancejpollard** [comment]
I think this is fixed now, yeah?
