### ISSUE TITLE
Gruntfile not found

### ISSUE THREAD

**Issue by ghost** [tower-archive/tower#390]
npm view grunt version
0.4.0

root@ps:/home/me/app# cake watch
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.

**Comment by thehydroimpulse** [comment]
Tower does not support grunt 0.4.0. Please downgrade to 0.3.*.

**Comment by ghost** [comment]
how do I do that?

**Comment by thehydroimpulse** [comment]
`npm install grunt@3.x.x -g`

**Comment by ghost** [comment]
^Croot@ps:/home/me/app# cake watch
Default database not set, using Memory store
Running "copy:stylesheets" (copy) task
Copied 2 files.

Running "copy:javascripts" (copy) task
Copied 34 files.

Running "copy:images" (copy) task
Copied 0 files.

Running "coffee:compile" (coffee) task

Running "less:bootstrap" (less) task

TypeError: Object #<Object> has no method 'options'
    at Object.<anonymous> (/home/me/app/node_modules/grunt-contrib-less/tasks/less.js:24:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt/lib/grunt/task.js:109:15)
    at Object.thisTask.fn (/usr/local/lib/node_modules/grunt/lib/grunt/task.js:58:16)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:343:36)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:346:11)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:346:11)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:346:11)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:346:11)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:346:11)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:346:11)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:346:11)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:319:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:346:11)
    at Task.start (/usr/local/lib/node_modules/grunt/lib/util/task.js:359:5)
    at Object.grunt.tasks (/usr/local/lib/node_modules/grunt/lib/grunt.js:143:8)
    at Object.module.exports [as cli](/usr/local/lib/node_modules/grunt/lib/grunt/cli.js:36:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt/bin/grunt:19:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:497:10)
    at process._tickCallback (node.js:427:13)
root@ps:/home/me/app#

**Comment by ghost** [comment]
I think these things should make it to the website tutorial guide, I nearly abandoned Tower.js out of frustration because of this issue but I really want to make this work, it looks like a very promising but these little quirks definitely need to be ironed out if it wants to gain traction of continued users and it's maturity.

**Comment by thehydroimpulse** [comment]
Yes, we are aware of that. Were working on the next version 0.5.0 that basically changes everything. 0.4.x isn't ready for use. I'd personally wait till 0.5.0 as to not waste your time on 0.4.x.

**Comment by ghost** [comment]
Thank you, and once again I really want Tower.js to thrive and I might have sounded blunt but there was no other way to put it. I'm glad it's already being looked at, I apologize I've been awake for the past 48 hours trying out various frameworks to no avail. I've really drawn the line at CompoundJS and Tower.js and leaning towards the latter.

I digress, I am going to look at this tomorrow..any temporary work around?

when is 0.5.0 coming out? I see there was a thread a month ago about it.

Thanks again for your great work!

**Comment by thehydroimpulse** [comment]
No worries. I can't talk about any specifics (of the new version), just wanted to let you know were still working on Tower. We'll annonce things when were ready. 

Haven't seen that error before, but there have been many weird errors on different platforms or setups. If things keep not working, I'd definitely wait till 0.5.0 where things will work.

Thanks.

**Comment by ghost** [comment]
I think this is grunt specific so I will research my findings there and post back the solution.

I look forward to 0.5.0, hopefully in the near future.

Cheers.

**Comment by thehydroimpulse** [comment]
A quick guess is that the less grunt task is for the newer 0.4.0 version and not 3.x.x.

**Comment by ghost** [comment]
What was the last version of grunt reported working? I installed 0.3.9 and it throws that message.

**Comment by ghost** [comment]
I installed 0.3.3, it complains about grunt-contrib-less, upon attemping to install the latter, it asks for grunt 0.4.0....

okay im going to bed for real now.

**Comment by thehydroimpulse** [comment]
I don't really remember. Try 0.3.5 or something. Make sure you have the grunt-contrib-less at version 0.3.0.

**Comment by btbinhtran** [comment]
Take a look at https://github.com/viatropos/tower/issues/388

Look at the last comment.

Other than that, wait for the 0.5.0 release. It will be out soon.

Cheers!
