### ISSUE TITLE
Arguments to path.join must be strings

### ISSUE THREAD

**Issue by deepanshumehndiratta** [tower-archive/tower#396]
I trying to set up a Tower Application. I'm getting this error on starting the server.
Node Version: 0.10.1

```
$ tower s
   info  - socket.io started
Tower development server listening on port 3000

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Tower.Application.Application.reopen._buildRequirePaths (/usr/local/lib/node_modules/tower/lib/tower-application/server/application.js:361:21)
    at Tower.Application.Application.reopen.selectPaths (/usr/local/lib/node_modules/tower/lib/tower-application/server/application.js:386:19)
    at Tower.Application.Application.reopen._loadMVC (/usr/local/lib/node_modules/tower/lib/tower-application/server/application.js:302:47)
    at Tower.Application.Application.reopen._loadApp (/usr/local/lib/node_modules/tower/lib/tower-application/server/application.js:307:12)
    at /usr/local/lib/node_modules/tower/lib/tower-application/server/application.js:100:28
    at process._tickCallback (node.js:415:13)
```

**Comment by pocesar** [comment]
doesn't work with node 0.10, stick with 0.8.22

**Comment by thehydroimpulse** [comment]
Tower 0.5.0 will work 100% on 0.10.

**Comment by deepanshumehndiratta** [comment]
I get the following error on downgrading to 0.8.22

Its been almost 3 days since I'm trying to set up Tower. Can some one tell me exact step by step procedure, since most resources I have found end up throwing some kind of error.

```
   create : test/vendor/javascripts/socket.io.js

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: socket hang up
    at createHangUpError (http.js:1373:15)
    at CleartextStream.socketCloseListener (http.js:1424:23)
    at CleartextStream.EventEmitter.emit (events.js:126:20)
    at SecurePair.destroy (tls.js:956:22)
    at process.startup.processNextTick.process._tickCallback (node.js:245:9)
```

**Comment by thehydroimpulse** [comment]
mmm. I've never seen this error before. I apologize for the complicated setup. I would just wait for 0.5.0 which is coming soon. It'll be a much more streamlined process.

**Comment by deepanshumehndiratta** [comment]
I was finally able to set-up Tower without any setup errors. But I have run into a ton of problems during runtime.
Please look into the following open issues: #397
