### ISSUE TITLE
Error when try to run towerjs app

### ISSUE THREAD

**Issue by panosru** [tower-archive/tower#45]
When I try to run a towerjs app I'm getting this errors:

```
root@dev:/home/panosru/domains/example.com/app# node server.js 
   info  - socket.io started
[Thu, 15 Mar 2012 09:50:25 GMT] INFO Tower development server listening on port 3000

info:  Name: design.io-watcher::app hook::listening                          Type: hook            Data: 5000
info:  Name: design.io-watcher::app hook::started                            Type: hook            Data: 5000
info:  Name: design.io-watcher::app hook::ready                              Type: hook            Data: {"name":"design.io-watcher::app","type":"hook","pk ... 
info:  Name: design.io-watcher::app ready                                    Type: hook            Data: {"name":"design.io-watcher::app","type":"hook","pk ... 
[Thu, 15 Mar 2012 09:50:29 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
[Thu, 15 Mar 2012 09:50:29 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
[Thu, 15 Mar 2012 09:50:30 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
[Thu, 15 Mar 2012 09:50:30 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
[Thu, 15 Mar 2012 09:50:30 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
[Thu, 15 Mar 2012 09:50:30 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
[Thu, 15 Mar 2012 09:50:30 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
[Thu, 15 Mar 2012 09:50:31 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
[Thu, 15 Mar 2012 09:50:31 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
[Thu, 15 Mar 2012 09:50:31 GMT] ERROR /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59: command not found: /var/lib/gems/1.8/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /home/panosru/domains/example.com/app
```

**Comment by panosru** [comment]
I updated to ruby 1.9.2 and latest version of ruby gems and now I get this errors:

```
root@dev:/home/panosru/domains/example.com/app# node server.js 
   info  - socket.io started
[Thu, 15 Mar 2012 09:59:23 GMT] INFO Tower development server listening on port 3000

info:  Name: design.io-watcher::app hook::listening                          Type: hook            Data: 5000
info:  Name: design.io-watcher::app hook::started                            Type: hook            Data: 5000
info:  Name: design.io-watcher::app hook::ready                              Type: hook            Data: {"name":"design.io-watcher::app","type":"hook","pk ... 
info:  Name: design.io-watcher::app ready                                    Type: hook            Data: {"name":"design.io-watcher::app","type":"hook","pk ... 
[Thu, 15 Mar 2012 09:59:30 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Thu, 15 Mar 2012 09:59:30 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Thu, 15 Mar 2012 09:59:30 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Thu, 15 Mar 2012 09:59:30 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Thu, 15 Mar 2012 09:59:30 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Thu, 15 Mar 2012 09:59:31 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Thu, 15 Mar 2012 09:59:31 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Thu, 15 Mar 2012 09:59:31 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Thu, 15 Mar 2012 09:59:31 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Thu, 15 Mar 2012 09:59:31 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/app/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
```

**Comment by lancejpollard** [comment]
This is for design.io which [temporarily] uses ruby to watch files.  Did you install ruby 1.9.2 with [RVM](http://beginrescueend.com/)?  If so, make sure you set RVM to use the ruby version you want as the default:

http://beginrescueend.com/rubies/default/

Otherwise just make sure you have the `rb-fsevents` gem installed (which design.io should have installed automatically, but if you installed a new version of ruby without running `npm install design.io` again, won't be installed):

```
gem install fs-events
```

Let me know if that helps, thanks.

**Comment by panosru** [comment]
@viatropos hello, no I didn't installed ruby with rvm, I used debian's package 

```
root@dev# ruby --version
ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-linux]
```

you can check the output of my issue [here](https://gist.github.com/4e159ffd10e1ab3107f4) as you can see the gem is installed (I tried rb-fsevents at first but it could not be found but in any case if you notice it is installed successfully by design.io so it shouldn't be the problem...)

It is a debian 6 64bit

**Comment by lancejpollard** [comment]
Oop, I meant to write this:

```
# rb-fsevent, not rb-fsevents or fs-events
gem install rb-fsevent
```

Try that.

In general, when you get these kind of dependency errors, just look at the stack trace to find what library it's saying is missing (no such file to load -- _rb-fsevent_):

```
[Thu, 15 Mar 2012 09:59:30 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
```

Then do `gem install x`.

**Comment by panosru** [comment]
@viatropos 

Hello, thanks a lot for the support, yes I saw the debug trace and I already tried to install `rb-fsevent` but I'm still getting errors when I run `node server.js`...

```
root@dev:/home/panosru/domains/example.com/test# gem install rb-fsevent
Successfully installed rb-fsevent-0.9.0
1 gem installed
Installing ri documentation for rb-fsevent-0.9.0...
Installing RDoc documentation for rb-fsevent-0.9.0...
root@dev:/home/panosru/domains/example.com/test# node server.js 
   info  - socket.io started
[Mon, 19 Mar 2012 22:11:26 GMT] INFO Tower development server listening on port 3000

info:  Name: design.io-watcher::test hook::listening                          Type: hook            Data: 5000
info:  Name: design.io-watcher::test hook::started                            Type: hook            Data: 5000
info:  Name: design.io-watcher::test hook::ready                              Type: hook            Data: {"name":"design.io-watcher::test","type":"hook","p ... 
info:  Name: design.io-watcher::test ready                                    Type: hook            Data: {"name":"design.io-watcher::test","type":"hook","p ... 
[Mon, 19 Mar 2012 22:11:58 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Mon, 19 Mar 2012 22:12:02 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Mon, 19 Mar 2012 22:12:04 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Mon, 19 Mar 2012 22:12:05 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Mon, 19 Mar 2012 22:12:05 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Mon, 19 Mar 2012 22:12:07 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require'
[Mon, 19 Mar 2012 22:12:07 GMT] ERROR :
[Mon, 19 Mar 2012 22:12:07 GMT] ERROR no such file to load -- rb-fsevent
[Mon, 19 Mar 2012 22:12:07 GMT] ERROR (
[Mon, 19 Mar 2012 22:12:07 GMT] ERROR LoadError
[Mon, 19 Mar 2012 22:12:07 GMT] ERROR )
[Mon, 19 Mar 2012 22:12:07 GMT] ERROR from <internal:lib/rubygems/custom_require>:29:in `require'
[Mon, 19 Mar 2012 22:12:07 GMT] ERROR from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Mon, 19 Mar 2012 22:12:08 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Mon, 19 Mar 2012 22:12:08 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- rb-fsevent (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require'
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR :
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR no such file to load -- rb-fsevent
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR (
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR LoadError
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR )
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR from <internal:lib/rubygems/custom_require>:29:in `require'
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR <internal:lib/rubygems/custom_require>:29:in `require'
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR :
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR no such file to load -- rb-fsevent
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR (
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR LoadError
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR )
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR from <internal:lib/rubygems/custom_require>:29:in `require'
[Mon, 19 Mar 2012 22:12:09 GMT] ERROR from /home/panosru/domains/example.com/test/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
```

Really strange and I really love the work you done with Tower, I want to try it but these errors prevent me :(

Thanks again for your support...

PS: Can't you make design.io not being depended on ruby gem? (I haven't seen the code of `design.io` but I'm curious if you have such plans)

**Comment by pyboosted** [comment]
I have some problems with rb-fsevent too. I installed ruby and gem using rvm. So, when i try: `node server` server starts and application works, but I see a lot of error messages in terminal:
`rvm use 1.9.3`
`node server`

>   info  - socket.io started
> [Wed, 21 Mar 2012 05:54:48 GMT] INFO Tower development server listening on port 3000
> 
> info:  Name: design.io-watcher::tower_app hook::listening                          Type: hook            Data: 5000
> info:  Name: design.io-watcher::tower_app hook::started                            Type: hook            Data: 5000
> info:  Name: design.io-watcher::tower_app hook::ready                              Type: hook            Data: {"name":"design.io-> watcher::tower_app","type":"hoo ... 
> info:  Name: design.io-watcher::tower_app ready                                    Type: hook            Data: {"name":"design.io-watcher::tower_app","type":"hoo ... 
> 
> [Wed, 21 Mar 2012 05:54:49 GMT] ERROR /home/pythonic/.rvm/gems/ruby-1.9.3-p0/gems/rb-fsevent-0.9.0/bin/fsevent_watch: 1: cannot open ��: No such file
> /home/pythonic/.rvm/gems/ruby-1.9.3-p0/gems/rb-fsevent-0.9.0/bin/fsevent_watch: 1: ������
>                                                                                               �t�
>                                                                                                   �����0: not found
> /home/pythonic/.rvm/gems/ruby-1.9.3-p0/gems/rb-fsevent-0.9.0/bin/fsevent_watch: 2: Syntax error: word unexpected (expecting ")")
> [Wed, 21 Mar 2012 05:54:49 GMT] ERROR /home/pythonic/.rvm/gems/ruby-1.9.3-p0/gems/rb-fsevent-0.9.0/bin/fsevent_watch: 1: cannot open ��: No such file
> /home/pythonic/.rvm/gems/ruby-1.9.3-p0/gems/rb-fsevent-0.9.0/bin/fsevent_watch: 1: ������
>                                                                                               �t�
>                                                                                                   �����0: not found
> /home/pythonic/.rvm/gems/ruby-1.9.3-p0/gems/rb-fsevent-0.9.0/bin/fsevent_watch: 2: Syntax error: word unexpected (expecting ")")

`rvm use 1.9.2`
`node server`

> info:  Name: design.io-watcher::tower_app hook::listening                          Type: hook            Data: 5000
> info:  Name: design.io-watcher::tower_app hook::started                            Type: hook            Data: 5000
> info:  Name: design.io-watcher::tower_app hook::ready                              Type: hook            Data: {"name":"design.io-watcher::tower_app","type":"hoo ... 
> info:  Name: design.io-watcher::tower_app ready                                    Type: hook            Data: {"name":"design.io-watcher::tower_app","type":"hoo ... 
> 
> [Wed, 21 Mar 2012 06:00:57 GMT] ERROR /home/pythonic/.rvm/gems/ruby-1.9.2-p290/gems/rb-fsevent-0.9.0/lib/rb-fsevent/fsevent.rb:115: in popen: Exec format error - /home/pythonic/.rvm/gems/ruby-1.9.2-p290/gems/rb-fsevent-0.9.0/bin/fsevent_watch  /var/www/tower_app (Errno::ENOEXEC)
>   from /home/pythonic/.rvm/gems/ruby-1.9.2-p290/gems/rb-fsevent-0.9.0/lib/rb-fsevent/fsevent.rb:115:in `pipe'
>   from /home/pythonic/.rvm/gems/ruby-1.9.2-p290/gems/rb-fsevent-0.9.0/lib/rb-fsevent/fsevent.rb:46:in`stop'
>   from /home/pythonic/.rvm/gems/ruby-1.9.2-p290/gems/rb-fsevent-0.9.0/lib/rb-fsevent/fsevent.rb:42:in `ensure in run'
>   from /home/pythonic/.rvm/gems/ruby-1.9.2-p290/gems/rb-fsevent-0.9.0/lib/rb-fsevent/fsevent.rb:42:in`run'
>   from /var/www/tower_app/node_modules/design.io/lib/design.io/listener/mac.rb:13:in `<main>'

As i understand - `rb-fsevent-0.9.9/bin/fsevent_watch` is a mac only binary, and it wouldnt run on Ubuntu. So, server starts, but design.io doesnt work here.

**Comment by lancejpollard** [comment]
Yeah, this is the one thing that's been causing the most problems.  Need to find a _good_ cross-platform file watcher solution for node.js.  Right now this ruby hack only works on Mac.

If you want to take a stab at it, check out design.io, which is modeled heavily after Guard:
- https://github.com/viatropos/design.io/tree/master/src/design.io/listener
- https://github.com/guard/guard/tree/master/lib/guard/listeners

I want to get rid of this ruby dependency though, but haven't found a good pure-node solution.  This is going to be the next big thing to focus on cleaning up once I finish a few things.

**Comment by rbraley** [comment]
This is a blocker for me as well please evaluate the pull request on https://github.com/viatropos/design.io/pull/9
