### ISSUE TITLE
fixtures ?

### ISSUE THREAD

**Issue by cbou** [tower-archive/tower#62]
Is it possible to load dummy data ?

I did not see any docs about this topic.

**Comment by lancejpollard** [comment]
No formal feature in here yet but I'm working on this.  It's going to work like Rails' seeds:

```
cake db:seed
```

That's a simple task that loads the file from `db/seeds.coffee`, in which you can write your scripts to add dummy data.

http://archives.ryandaigle.com/articles/2009/5/13/what-s-new-in-edge-rails-database-seeding

To make this happen right now, I'd just add a task to `Cakefile` like this:

``` coffeescript
task 'db:seed', ->
  require('tower').Application.instance().initialize()

  require('./db/seeds')
```

And then in `db/seeds.coffee`, something like:

``` coffeescript
# db/seeds.coffee

async = require('async')
user  = null

async.series [
  # clear any existing data
  (done) => App.User.destroy(done)
  (done) => App.Post.destroy(done)

  # create users
  (done) => App.User.create
    name:   "Admin"
    email:  "admin@example.com"
    (error, record) =>
      user = record
      done()

  # create posts
  (done) => user.posts().create(title: "Post 1", done)
  (done) => user.posts().create(title: "Post 2", done)
], (error) =>
  if error
    console.log "Something went wrong creating seed data... Try running again."
  else
    console.log "Successfully created seed data!"
```

As a side note, Tower will also use the idea of "factories" to make creating dummy/test data easier, as well as fakers.
- https://github.com/thoughtbot/factory_girl
- https://github.com/marak/Faker.js

However, Tower most likely won't be implementing this as "fixtures" the way Rails did, using YAML and all that.  Factories + db/seeds are much more powerful.

http://railscasts.com/episodes/158-factories-not-fixtures?view=asciicast

Hope that helps.

**Comment by cbou** [comment]
Thanks, I have a problem when calling `cake db:seed` :

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot read property 'slaveOk' of undefined
    at new Collection (.../node_modules/mongodb/lib/mongodb/collection.js:52:65)
    at MongoDB.collection (.../node_modules/tower/lib/tower/server/store/mongodb/database.js:45:26)
    at MongoDB.find (.../node_modules/tower/lib/tower/server/store/mongodb/finders.js:16:10)
    at Scope._each (.../node_modules/tower/lib/tower/model/scope/persistence.js:106:23)
    at Scope._destroy (.../node_modules/tower/lib/tower/model/scope/persistence.js:99:19)
    at Scope.destroy (.../node_modules/tower/lib/tower/model/scope/persistence.js:34:17)
    at Function.destroy (.../node_modules/tower/lib/tower/model/scopes.js:58:41)
    at .../db/seeds.js:15:25
    at .../node_modules/async/lib/async.js:486:21
    at .../node_modules/async/lib/async.js:185:13
```

My seed look like this:

``` coffeescript
async = require('async')
person1  = null
person2  = null
person3  = null

async.series [
  # clear any existing data
  (done) => App.Person.destroy(done)
  (done) => App.Project.destroy(done)

  # create users
  (done) => App.Person.create
    name:   "person1"
    (error, record) =>
      person1 = record
      availabilities = []
      assignments = []
      done()
  (done) => App.Person.create
    name:   "person2"
    (error, record) =>
      person2 = record
      availabilities = []
      assignments = []
      done()
  (done) => App.Person.create
    name:   "person3"
    (error, record) =>
      person3 = record
      availabilities = []
      assignments = []
      done()

], (error) =>
  if error
    console.log "Something went wrong creating seed data... Try running again."
  else
    console.log "Successfully created seed data!"
```

Do you have any idea ?

**Comment by lancejpollard** [comment]
Looks like you'll need to wait for MongoDB to initialize, here's the updated task and seed file:

``` coffeescript
task 'db:seed', ->
  # needed to put require inside callback
  require('tower').Application.instance().initialize =>
    require './db/seeds'
```

``` coffeescript
async = require('async')
person1  = null
person2  = null
person3  = null

async.series [
  # clear any existing data
  (done) => App.Person.destroy(done)
  (done) => App.Project.destroy(done)

  # create users
  (done) => App.Person.create
    name:   "person1"
    (error, record) =>
      person1 = record
      availabilities = []
      assignments = []
      done()
  (done) => App.Person.create
    name:   "person2"
    (error, record) =>
      person2 = record
      availabilities = []
      assignments = []
      done()
  (done) => App.Person.create
    name:   "person3"
    (error, record) =>
      person3 = record
      availabilities = []
      assignments = []
      done()

], (error) =>
  if error
    console.log "Something went wrong creating seed data... Try running again."
  else
    console.log "Successfully created seed data!"
  process.exit() # close task
```

**Comment by cbou** [comment]
Thanks it works :)

**Comment by lancejpollard** [comment]
sweet.
