### ISSUE TITLE
Two scaffolds error

### ISSUE THREAD

**Issue by searchinnerpeace** [tower-archive/tower#71]
Fresh tower install.

Code used:
tower g scaffold Post01 title:string body:text
tower g scaffold Post02 title:string body:text

Insert some data on Post01: ok
Insert some data on Post02: ok

Mongodb is working.

Click on Post01(in navbar): everything is ok
Click on Post02:  body don't render.

Console error

TypeError: Cannot read property 'length' of undefined
    at View.<anonymous> (eval at <anonymous> (eval at <anonymous> (/home/user/dev/node/app/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12)))
    at Object.render_contents (eval at <anonymous> (/home/user/dev/node/app/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
    at Object.render_tag (eval at <anonymous> (/home/user/dev/node/app/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
    at View.<anonymous> (eval at <anonymous> (/home/user/dev/node/app/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
    at Object.tag (eval at <anonymous> (/home/user/dev/node/app/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
    at Table.tag (/home/user/dev/node/app/node_modules/tower/lib/tower/view/component.js:29:26)
    at Table._section (/home/user/dev/node/app/node_modules/tower/lib/tower/view/table.js:113:10)
    at Table.body (/home/user/dev/node/app/node_modules/tower/lib/tower/view/table.js:102:17)
    at eval at <anonymous> (eval at <anonymous> (/home/user/dev/node/app/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
    at View.<anonymous> (/home/user/dev/node/app/node_modules/tower/lib/tower/view/table.js:42:18)

Restart server and try again:

Click on Post02: everything is ok
Click on Post01:  body don't render.

**Comment by jamespeerless** [comment]
Hey this is same issue as #30: https://github.com/viatropos/tower/issues/30

Fix suggested in that thread works for me but it's not part of repo yet.

**Comment by searchinnerpeace** [comment]
Thanks! I will try this

**Comment by lancejpollard** [comment]
Fixed in latest release. Try updating tower with `npm install tower` in your app and `npm install tower -g` globally, or generate a new app.  Let me know if that works.
