### ISSUE TITLE
Models not passed as model instance

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#78]
With the latest towerJS release, I have the problem, that whenever I call Model.find, for example, the passed resources are not instances of a model class anymore, but plain objects.

This causes this code to fail:

```
 App.Photo.find @params.id, (error, resource) =>
    console.log resource.id
```

I now instead have to do this:

```
 App.Photo.find @params.id, (error, resource) =>
    console.log resource.attributes.id
```

This bug has to be introduced somewhere within the last two days.

Maybe we should expand our unit tests in that area?

**Comment by lancejpollard** [comment]
I'm not sure I understand.  The first example is incorrect, the second one is correct.  This is how it's supposed to work:

``` coffeescript
App.Photo.find @params.id, (error, resource) =>
    console.log resource.attributes.id
```

But, the way you access attributes is like this:

``` coffeescript
App.Photo.find @params.id, (error, resource) =>
    console.log resource.get('id')
```

To get your first example working, you can (although I haven't checked recently) set `Tower.accessors = true`, which will use `Object.defineProperty` to create getters/setters in Node.js and the browsers that support them (newer browsers).  Then you can do this:

``` coffeescript
App.Photo.find @params.id, (error, resource) =>
    console.log resource.id
```

But, I suspect, being able to do `resource.id` previously _was_ a bug, now it's fixed?  Or is this happening on the client?  Let me know.  Thanks for all your posts.

**Comment by sebastianhoitz** [comment]
I noticed this with forms. I have a scaffold that was generated using the generator. With the latest tower version, no data is displayed inside my forms anymore.

I also get this error:

```
TypeError: Cannot read property 'required' of undefined
at new Field (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/lib/tower/view/form/field.js:53:25)
at Builder.field (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/lib/tower/view/form/builder.js:105:12)
at eval at <anonymous> (eval at <anonymous> (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
at Builder.render (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/lib/tower/view/form/builder.js:138:12)
at View.<anonymous> (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/lib/tower/view/form/fieldset.js:37:30)
at Object.render_contents (eval at <anonymous> (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
at Object.render_tag (eval at <anonymous> (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
at View.<anonymous> (eval at <anonymous> (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
at Object.tag (eval at <anonymous> (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/node_modules/coffeekup/lib/coffeekup.js:344:12))
at Fieldset.tag (/Library/WebServer/Documents/prisma/prisma-box-app_towerjs/node_modules/tower/lib/tower/view/component.js:29:26)
```

That happens for the field "filename" on one of my models. Prior to using towerJS 0.4.0-2, this used to work.

**Comment by sebastianhoitz** [comment]
Ok, the error was on my side. I did not pass the model to the view.

However, now that I do this, the form helper still seems to have problems showing the values in the form. But I will open a separate issue for that.

**Comment by contentfree** [comment]
The documentation at http://towerjs.org/models says that `resource.id` should work (according to the section "Getting and Setting Field Values"). That section shows the `user.get("firstName")` method as well as the getter/setter method `user.firstName` method. I'm finding that the getter/setter doesn't work. 

My example:

```
    test "name", ->
      company.name.should.equal("Test Company") # Fails with "TypeError: Cannot read property 'should' of undefined"
      company.get("name").should.equal("Test Company") # Works
```

So are getters/setters supposed to be working currently?
