### ISSUE TITLE
Can't configure Tower to use Memory store for tests

### ISSUE THREAD

**Issue by contentfree** [tower-archive/tower#83]
I'm trying to run `npm test` and getting the failure:

```
  1) "before all" hook

  ✖ 1 of 9 tests failed:

  1)  "before all" hook:
     Error: failed to connect to [127.0.0.1:27017]
      at [object Object].<anonymous> (/Users/dave/Sites/path/node_modules/mongodb/lib/mongodb/connection/server.js:408:73)
      at [object Object].emit (events.js:88:20)
      at [object Object].<anonymous> (/Users/dave/Sites/path/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:96:15)
      at [object Object].emit (events.js:70:17)
      at Socket.<anonymous> (/Users/dave/Sites/path/node_modules/mongodb/lib/mongodb/connection/connection.js:385:10)
      at Socket.emit (events.js:67:17)
      at Array.0 (net.js:319:25)
      at EventEmitter._tickCallback (node.js:192:40)
```

I have tried to find every place where mongo is used explicitly or where a store isn't explicitly set. This includes:
1. Setting `Tower.Model.store Tower.Store.Memory` in `application.coffee`
2. Changing the `beforeEach` in `test/server.coffee` to only do `Tower.Store.Memory.clean(done)`
3. Commenting out everything in `config/databases.coffee`

Where else is the use of Mongo being used as the default or being set explicitly?

PS. Maybe the default configuration should be to use the Memory store when running tests.

**Comment by lancejpollard** [comment]
https://github.com/viatropos/tower/issues/80#issuecomment-5061913

**Comment by lancejpollard** [comment]
You can now run all tests for a specific store (defaults to memory):

```
mocha $(find test -name "*Test.coffee") --store mongodb
```

These are abstracted away into the Makefile:

```
make test-memory
make test-mongodb
# all of them:
make test
```
