### ISSUE TITLE
Coffee-script dependency issue?

### ISSUE THREAD

**Issue by webdesserts** [tower-archive/tower#9]
I ran into this issue the first time I ran server.js

```
mcmullins@ubuntu:~/sites/todo$ node server.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:378:11)
    at Object.<anonymous> (/home/mcmullins/.node_libraries/coffee-script@1.2.0/index.js:4:21)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/mcmullins/sites/todo/server.js:1:63)
    at Module._compile (module.js:441:26)
```

it was fixed by running a fresh install of coffee-script.

```
mcmullins@ubuntu:~/sites/todo$ npm install coffee-script
```

Maybe an issue with how a previous version of npm installed it? Probably isn't your fault, but I thought I would let you know in case anyone else runs into this problem.

Thanks for all the help! Trying it out now, It's looking great!

**Comment by lancejpollard** [comment]
Thanks for posting, yeah I've had some random issues like this before with coffee-script modules installed in different places, independent of Tower.

Not sure what the fix is but installing coffee-script like you did works, will keep any eye out.
