### ISSUE TITLE
Express 3.0 breaks tower

### ISSUE THREAD

**Issue by hadesgames** [tower-archive/tower#94]
Currently npm installs express 3.0.0alpha1 by default.

This versions breaks the server:

```
node server.js 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object function createApplication() {
  var app = connect();
  utils.merge(app, proto);
  app.request = { __proto__: req };
  app.response = { __proto__: res };
  app.init();
  return app;
} has no method 'createServer'
    at App.Application (/private/tmp/express_crash/node_modules/tower/lib/tower/server/application.js:92:54)
    at new App (/private/tmp/express_crash/config/application.coffee:13:40)
    at Object.<anonymous> (/private/tmp/express_crash/config/application.coffee:44:33)
    at Object.<anonymous> (/private/tmp/express_crash/config/application.coffee:46:4)
    at Module._compile (module.js:441:26)
    at Object..coffee (/private/tmp/express_crash/node_modules/coffee-script/lib/coffee-script/coffee-script.js:22:21)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
```

If I manually revert to express 2.5.9 everything works.

**Comment by kristianmandrup** [comment]
See https://github.com/visionmedia/express/issues/867

And https://github.com/visionmedia/express/commit/75c29bd42a809f33ff84738f93aa7acc4c955cae

Not it's just `var app = express();`

**Comment by kristianmandrup** [comment]
In tower/lib/tower/server/application.js line 87

`this.server || (this.server = require('express').createServer());`

should likely just be:

`this.server || (this.server = require('express'));`

**Comment by lancejpollard** [comment]
Coercing to express `2.x` in package.json until we can make all the updates to get it working with express 3.
